# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgo < Formula
  desc "A beautiful, interactive TUI for go test"
  homepage "https://github.com/zlrkw11/tgo"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.1/tgo_0.2.1_darwin_amd64.tar.gz"
      sha256 "95219224112eece059b11fdfd4944b7abad5aec230349dae45e73a93e9d9e39c"

      define_method(:install) do
        bin.install "tgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.1/tgo_0.2.1_darwin_arm64.tar.gz"
      sha256 "362f87b2ffd4c818a161115fb0b2146fe0796b3dc7f0c468a83632e0f327fd47"

      define_method(:install) do
        bin.install "tgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.1/tgo_0.2.1_linux_amd64.tar.gz"
      sha256 "66fb8bd4ef926b24481a3df4ef70885bab8dae3248b13c83b9ba9974db15832a"
      define_method(:install) do
        bin.install "tgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.1/tgo_0.2.1_linux_arm64.tar.gz"
      sha256 "b7c45ff8aeb761f607345a0c8af94e37ec218e72d8a71fbfec2bf731065228c7"
      define_method(:install) do
        bin.install "tgo"
      end
    end
  end
end
