# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgo < Formula
  desc "A beautiful, interactive TUI for go test"
  homepage "https://github.com/zlrkw11/tgo"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.1/tgo_0.2.1_darwin_amd64.tar.gz"
      sha256 "5df7b83b035582a1cdb4c28e19d3c699951f56b656f1d022ebe1ff6be5b7fbf7"

      define_method(:install) do
        bin.install "tgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.1/tgo_0.2.1_darwin_arm64.tar.gz"
      sha256 "8cd08140eda537abc0f18ef7f23591639c7d5cb6396ee9e136cd975024774353"

      define_method(:install) do
        bin.install "tgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.1/tgo_0.2.1_linux_amd64.tar.gz"
      sha256 "17bdb5030592bcd31b81d1803f272e45305443a2bbf9be70afb5b2b06b26347c"
      define_method(:install) do
        bin.install "tgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.1/tgo_0.2.1_linux_arm64.tar.gz"
      sha256 "6b5baf69f6479203b7f7196e9a4d7040885d79bec8418be1be9bed6ff3af5d56"
      define_method(:install) do
        bin.install "tgo"
      end
    end
  end
end
