# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgo < Formula
  desc "A beautiful, interactive TUI for go test"
  homepage "https://github.com/zlrkw11/tgo"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.0/tgo_0.2.0_darwin_amd64.tar.gz"
      sha256 "c93a44b32b762dce39a61c82ac9730e0050a9771e5d9dc266151c1bd417cbcfd"

      define_method(:install) do
        bin.install "tgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.0/tgo_0.2.0_darwin_arm64.tar.gz"
      sha256 "72007cfdc7b72236db2584666e6e8d696b50cc178bba9566069960df7807034c"

      define_method(:install) do
        bin.install "tgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.0/tgo_0.2.0_linux_amd64.tar.gz"
      sha256 "5429e1a2aaf5d418769ae8867dc24563dd23e24d0f582153aea74d00cd8a593a"
      define_method(:install) do
        bin.install "tgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zlrkw11/tgo/releases/download/v0.2.0/tgo_0.2.0_linux_arm64.tar.gz"
      sha256 "d432a3dd9f83c39aa8031b6193f50518337450073b77cf3487a42606adbbf106"
      define_method(:install) do
        bin.install "tgo"
      end
    end
  end
end
